variable "nlbname" {}
variable "public_subnet_id" {}
variable "environment" {}
variable "tgname" {}
variable "vpc_id" {}
variable "private-instance" {}
variable "public-instance" {}
variable "certificate_arn" {}
variable "sg_id" {}
